name: Delete
description: Delete a Subdomain
title: "Delete"
labels: []
projects: []
assignees: []
body:
  - type: input
    id: domain
    attributes:
      label: Subdomain Name
      description: What subdomain do you want to delete? ex. something.possibly-is.gay
      value: ".possibly-is.gay"
    validations:
      required: true
      
  - type: checkboxes
    id: check
    attributes:
      label: Agreement
      options:
        - label: I have ensured that this subdomain is mine
          required: true
          
  - type: input
    id: confirm
    attributes:
      label: Type your domain name + DELETE to confirm
      description: ex. something.possibly-is.gay DELETE
    validations:
      required: true
