name: Get Info
description: Get Info on a Subdomain
title: "Get Info"
labels: []
projects: []
assignees: []
body:
  - type: input
    id: domain
    attributes:
      label: Subdomain Name
      description: What subdomain do you want to get info on? ex. something.possibly-is.gay
      value: ".possibly-is.gay"
    validations:
      required: true
